<H1>MACHINE LEARNING</H1>

<H3>TYPES</H3>

<pre>1)Supervised Learning
    1)Regression<pre>
        1)Linear Regression
        2)Polynomial Regression
        3)Lasso Regression
        4)Rigid Regression
    2)Classification<pre>
        1)Logistic Regression
        2)Naive Bayes
        3)KNN: K Nearest Neighbors
        4)SVM: Support Vector Machine</pre>

<h3>MACHINE LEARNING PROCEDURE</H3>
<PRE>    Step 1: Data Reading
    Step 2: Data Cleaning
    Step 3: Data analysis
    Step 4: Encoding
    Step 5: I/O Creation
    Step 6: Train-Test-Split
    Step 7: Standard Scalar Transform
    Step 8: Machine Learning Model
    step 9: Prediction
    Step 10:Accuracy</pre>

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
ad=pd.read_csv(r"C:\Users\mishr\OneDrive\Desktop\advertising.csv")
ad

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [16]:
ip=ad.drop('Sales',axis=1)
op=ad.Sales

In [17]:
ip.head()

      TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [18]:
op.head()

0    22.1
1    10.4
2    12.0
3    16.5
4    17.9
Name: Sales, dtype: float64

In [19]:
import sklearn
print(sklearn.__version__)

1.7.2

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ip,op,train_size=0.8)

In [21]:
x_train

        TV  Radio  Newspaper
2     17.2   45.9       69.3
12    23.8   35.1       65.9
198  283.6   42.0       66.2
155    4.1   11.6        5.7
96   197.6    3.5        5.9
..     ...    ...        ...
140   73.4   17.0       12.9
165  234.5    3.4       84.8
10    66.1    5.8       24.2
33   265.6   20.0        0.3
150  280.7   13.9       37.0

[160 rows x 3 columns]

In [22]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(160, 3)
(160,)
(40, 3)
(40,)

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit(x_test)

In [24]:
x_train

array([[-1.51961512,  1.53479843,  1.74614633],
       [-1.44206463,  0.81757963,  1.59364202],
       [ 1.61060476,  1.27580275,  1.60709828],
       [-1.6735411 , -0.74303536, -1.10658138],
       [ 0.60009834, -1.28094946, -1.09761053],
       [ 0.57424818,  1.65433489,  1.0105373 ],
       [ 0.48494761, -0.11214845, -0.93613538],
       [ 0.98197577,  0.99688433,  1.74166091],
       [-1.38566427, -1.41376775,  0.11793854],
       [-0.06143086,  0.2663837 ,  0.7100141 ],
       [ 0.00906959,  0.07379717, -0.50553497],
       [-0.98968676, -0.67662621, -0.54141834],
       [-0.8392858 ,  0.81093871,  1.00156646],
       [-0.54200891, -0.87585365, -1.20077522],
       [ 1.3485781 ,  1.32228915,  1.09127488],
       [ 0.61537344,  1.76723045,  1.32900219],
       [-0.14368138, -1.18797665, -0.94510622],
       [-1.40681441,  0.67812041, -0.49656413],
       [ 0.4508724 ,  1.40198013, -1.28599821],
       [ 0.86917505,  0.69140224,  0.33772416],
       [-0.83693579, -0.16527577,  0.09551143],
       [ 1.63880494, -0.59029432, -1.19628979],
       [ 0.03844478, -1.42704958, -0.27229308],
       [-0.43155821, -0.56373066,  0.05962806],
       [ 0.93145045, -0.96882646,  1.17201245],
       [ 1.61882982, -0.80944451, -1.07518343],
       [-1.56779043, -1.48681782, -0.21398261],
       [ 1.09007646, -0.48403968, -0.13773046],
       [ 0.86095   ,  0.71132499,  0.66067447],
       [ 0.70937404, -0.95554463, -0.17809924],
       [ 1.09595149, -1.24110397,  0.29286995],
       [-1.500815  , -0.07230296,  0.89840178],
       [ 0.83627484,  0.71132499,  1.28414798],
       [-0.35870775, -1.00203103, -0.32611814],
       [-1.62066576, -1.37392226, -1.31739616],
       [-0.6183844 ,  1.37541647,  0.9028872 ],
       [ 0.62594851, -1.34071769, -0.41134113],
       [ 0.86682504,  1.74066679, -1.2187169 ],
       [ 1.06775131, -1.17469482, -0.30817645],
       [-0.89216114, -0.4508351 ,  0.46780137],
       [ 1.27925266,  0.27302461, -1.11555222],
       [ 0.96082564, -0.39106687, -0.18707009],
       [ 0.35804681,  0.70468407,  0.37360753],
       [ 0.52372286,  0.39256108, -0.54590376],
       [ 0.40269709, -0.79616268,  1.25723545],
       [ 0.49199766, -0.31137589, -0.21398261],
       [-1.21528819,  0.25974278,  0.21213238],
       [-1.4209145 ,  1.0765753 , -0.94510622],
       [ 1.65760506,  1.3422119 ,  1.85828186],
       [ 0.62594851, -1.30751312,  0.18970527],
       [ 1.00547592, -0.9422628 , -0.97201875],
       [-0.77936042, -1.51338148, -0.94959164],
       [ 0.89150019, -1.22782214,  0.87148925],
       [ 0.80924967,  0.05387442,  1.22135208],
       [-1.25758846,  1.21603452, -1.10209596],
       [ 0.55427305,  0.83750237,  2.02872785],
       [ 0.29107138,  1.12306171,  0.32875332],
       [-0.43155821,  1.66097581,  0.94325599],
       [-0.8240107 , -1.46025416, -0.69840807],
       [-1.49376496, -0.4508351 , -0.3620015 ],
       [-1.19883808,  1.09649805,  0.66067447],
       [-0.20125675, -1.13484933,  0.04168638],
       [ 0.78692453,  1.3422119 ,  0.1538219 ],
       [ 1.69403029, -1.24110397, -0.98098959],
       [-0.93563641, -0.73639444,  0.28838453],
       [ 0.78574952,  0.12028357, -0.77466023],
       [ 0.42384722,  1.55472117,  1.27069171],
       [-0.10138111,  1.568003  ,  1.28414798],
       [-0.24473202,  0.93711609,  2.190203  ],
       [ 0.33572166, -0.01917564,  0.05065722],
       [ 0.22409595, -0.84928999, -0.57281629],
       [-0.12135624, -0.23832583, -0.6176705 ],
       [ 0.2781463 , -0.99539012,  0.2166178 ],
       [ 0.11834528, -1.34071769, -0.98996043],
       [-0.30583241,  0.37927925, -0.7253206 ],
       [-0.07318093, -1.38720409, -0.95856249],
       [ 0.23819604,  1.27580275, -1.20077522],
       [-1.27521357,  1.1629072 , -0.82848528],
       [ 0.34277171, -0.49068059, -1.25460027],
       [-0.27528222,  0.78437505, -0.80605817],
       [-0.65950966, -1.49345873, -0.32163271],
       [ 0.19707078,  0.58514761,  1.0105373 ],
       [-1.06136221, -1.13484933, -0.03008035],
       [-1.49141494, -0.1785576 , -0.59972881],
       [ 0.75519933,  1.78051227,  0.32875332],
       [ 0.95730061,  0.99024341,  0.07308433],
       [ 1.71988046,  0.36599742,  0.57545147],
       [-0.39513298, -0.3578623 ,  0.36912211],
       [-0.82518571,  0.3128701 , -0.64458302],
       [-0.61485937, -1.18797665, -0.99893127],
       [-0.8240107 ,  0.25974278, -0.3620015 ],
       [ 0.74109924, -0.14535302, -0.88231033],
       [ 1.49427902,  0.40584291,  1.31554592],
       [ 1.22637732,  0.91055243,  1.88070896],
       [ 0.48612262, -0.37114413, -0.55936002],
       [-0.4926586 , -1.13484933,  0.18073443],
       [ 1.41437852,  1.39533922, -1.13797932],
       [ 0.03726977,  0.8507842 , -1.09312511],
       [-0.84398583,  1.76723045,  0.68758699],
       [-0.68418482,  0.1800518 ,  1.93004859],
       [ 0.65767371, -0.03245747,  0.05514264],
       [-0.18128162,  1.32893007, -0.06596372],
       [ 0.91030031, -1.35399952, -0.6625247 ],
       [-0.08610602, -0.56373066, -0.21398261],
       [-1.51961512, -1.24110397,  0.05514264],
       [-0.13310631,  1.25588   ,  0.69655784],
       [ 0.97492572,  0.63163401,  1.96593196],
       [-1.35158906,  0.12028357, -1.26357111],
       [ 0.60009834,  0.03395168, -0.7253206 ],
       [-0.17423158, -0.29145315,  0.18970527],
       [ 0.6870489 ,  1.48167111, -0.48310787],
       [ 1.36737822, -1.28094946, -0.48759329],
       [ 0.35804681, -0.8957764 , -1.07518343],
       [-1.1541878 ,  1.60784849, -0.98098959],
       [-1.61949076,  1.73402587,  2.00181533],
       [ 1.52952925, -1.36064044, -0.29920561],
       [-0.34460766, -0.537167  , -1.12003764],
       [-1.2164632 ,  0.20661546, -0.44273908],
       [ 0.54839802, -0.29145315,  1.58467118],
       [ 1.57065451, -0.84264908, -0.40237029],
       [ 0.94790055, -0.46411693,  0.87597467],
       [-1.42796454, -0.78288085, -0.03008035],
       [-1.50199001, -0.70983078, -0.31266187],
       [-0.59723426, -1.42040867, -1.03032922],
       [ 0.4508724 , -0.11878936, -0.37545777],
       [ 0.82099975,  1.25588   ,  0.41397632],
       [-1.56661542, -0.45747602,  0.86251841],
       [ 0.89150019, -1.28759037, -0.77466023],
       [-0.91096126, -0.8957764 , -1.32188158],
       [-0.30935743, -0.21176217, -0.84194154],
       [ 1.09947652, -1.02859469, -0.97201875],
       [-0.57608413, -1.00867195, -1.03930006],
       [ 1.5847546 ,  1.11642079,  1.14061451],
       [ 1.0971265 ,  1.24259817, -0.5324475 ],
       [ 1.13590175,  1.74066679,  0.6247911 ],
       [ 0.0584199 ,  1.22931634,  1.26172087],
       [-0.08493101, -0.55044883, -0.90473743],
       [-0.57960915, -1.41376775, -0.01662409],
       [ 1.07715137,  0.76445231, -1.12452306],
       [-1.63594086,  0.35271559,  0.49471389],
       [-0.04263074,  0.43240657, -0.79708733],
       [-1.52314014,  1.3886983 ,  2.64771594],
       [-1.658266  ,  0.47225206, -0.9406208 ],
       [ 0.67647383,  0.6714795 ,  0.70104326],
       [ 0.25699616, -1.04187652, -0.78811649],
       [-1.13421267, -0.74303536, -0.53693292],
       [-0.45975839, -0.5836534 , -0.87333949],
       [-1.58424053,  0.93711609,  0.66515989],
       [-1.51139007,  0.9836025 , -0.39339945],
       [-1.42678953,  0.19333363,  0.57993689],
       [-0.83458577, -0.79616268, -1.09312511],
       [-1.71349135,  1.11642079, -0.97201875],
       [ 1.72810551,  0.32615193, -1.28151279],
       [-0.92506135,  0.91719335,  3.75112949],
       [ 1.39440339, -1.32079495,  0.56648063],
       [-0.85926093, -0.38442596, -0.78363107],
       [ 1.0336761 , -1.28759037,  2.44138658],
       [-0.94503647, -1.12820842, -0.27677851],
       [ 1.39910342, -0.18519851, -1.34879411],
       [ 1.57652955, -0.59029432,  0.29735537]])