POKEMON DATASET

In [1]:
import pandas as pd
import numpy as np

In [2]:
pk=pd.read_csv(r"C:\Users\mishr\Downloads\pokemon.csv")
pk

,Name,Type 1,Type 2,Combat Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
146,Dratini,Dragon,NaN,300,41,64,45,50,50,50,1,False
147,Dragonair,Dragon,NaN,420,61,84,65,70,70,70,1,False
148,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
149,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
150,Mew,Psychic,NaN,600,100,100,100,100,100,100,1,True

In [3]:
pk.isnull().sum()

Name             0
Type 1           0
Type 2          84
Combat Power     0
HP               0
Attack           0
Defense          0
Sp. Atk          0
Sp. Def          0
Speed            0
Generation       0
Legendary        0
dtype: int64

In [4]:
d=pk.describe(include='all')
d

,Name,Type 1,Type 2,Combat Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
count,151,151,67,151.00000,151.000000,151.000000,151.000000,151.000000,151.000000,151.000000,151.0,151
unique,151,15,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,Bulbasaur,Water,Poison,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,1,28,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146
mean,NaN,NaN,NaN,407.07947,64.211921,72.549669,68.225166,67.139073,66.019868,69.000000,1.0,NaN
std,NaN,NaN,NaN,99.74384,28.590117,26.596162,26.916704,28.534199,24.197926,26.935726,0.0,NaN
min,NaN,NaN,NaN,195.00000,10.000000,5.000000,5.000000,15.000000,20.000000,15.000000,1.0,NaN
25%,NaN,NaN,NaN,320.00000,45.000000,51.000000,50.000000,45.000000,49.000000,46.500000,1.0,NaN
50%,NaN,NaN,NaN,405.00000,60.000000,70.000000,65.000000,65.000000,65.000000,70.000000,1.0,NaN
75%,NaN,NaN,NaN,490.00000,80.000000,90.000000,84.000000,87.500000,80.000000,90.000000,1.0,NaN
max,NaN,NaN,NaN,680.00000,250.000000,134.000000,180.000000,154.000000,125.000000,150.000000,1.0,NaN

In [5]:
for i in pk.columns:
    print(i,':','\n',pk[i].unique(),'\n')

Name :
 ['Bulbasaur' 'Ivysaur' 'Venusaur' 'Charmander' 'Charmeleon' 'Charizard'
 'Squirtle' 'Wartortle' 'Blastoise' 'Caterpie' 'Metapod' 'Butterfree'
 'Weedle' 'Kakuna' 'Beedrill' 'Pidgey' 'Pidgeotto' 'Pidgeot' 'Rattata'
 'Raticate' 'Spearow' 'Fearow' 'Ekans' 'Arbok' 'Pikachu' 'Raichu'
 'Sandshrew' 'Sandslash' 'Nidoran♀' 'Nidorina' 'Nidoqueen' 'Nidoran♂'
 'Nidorino' 'Nidoking' 'Clefairy' 'Clefable' 'Vulpix' 'Ninetales'
 'Jigglypuff' 'Wigglytuff' 'Zubat' 'Golbat' 'Oddish' 'Gloom' 'Vileplume'
 'Paras' 'Parasect' 'Venonat' 'Venomoth' 'Diglett' 'Dugtrio' 'Meowth'
 'Persian' 'Psyduck' 'Golduck' 'Mankey' 'Primeape' 'Growlithe' 'Arcanine'
 'Poliwag' 'Poliwhirl' 'Poliwrath' 'Abra' 'Kadabra' 'Alakazam' 'Machop'
 'Machoke' 'Machamp' 'Bellsprout' 'Weepinbell' 'Victreebel' 'Tentacool'
 'Tentacruel' 'Geodude' 'Graveler' 'Golem' 'Ponyta' 'Rapidash' 'Slowpoke'
 'Slowbro' 'Magnemite' 'Magneton' "Farfetch'd" 'Doduo' 'Dodrio' 'Seel'
 'Dewgong' 'Grimer' 'Muk' 'Shellder' 'Cloyster' 'Gastly' 'Haunter'
 'Gengar' 'Onix' 'Drowzee' 'Hypno' 'Krabby' 'Kingler' 'Voltorb'
 'Electrode' 'Exeggcute' 'Exeggutor' 'Cubone' 'Marowak' 'Hitmonlee'
 'Hitmonchan' 'Lickitung' 'Koffing' 'Weezing' 'Rhyhorn' 'Rhydon' 'Chansey'
 'Tangela' 'Kangaskhan' 'Horsea' 'Seadra' 'Goldeen' 'Seaking' 'Staryu'
 'Starmie' 'Mr. Mime' 'Scyther' 'Jynx' 'Electabuzz' 'Magmar' 'Pinsir'
 'Tauros' 'Magikarp' 'Gyarados' 'Lapras' 'Ditto' 'Eevee' 'Vaporeon'
 'Jolteon' 'Flareon' 'Porygon' 'Omanyte' 'Omastar' 'Kabuto' 'Kabutops'
 'Aerodactyl' 'Snorlax' 'Articuno' 'Zapdos' 'Moltres' 'Dratini'
 'Dragonair' 'Dragonite' 'Mewtwo' 'Mew']

Type 1 :
 ['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon']

Type 2 :
 ['Poison' nan 'Flying' 'Ground' 'Fairy' 'Grass' 'Fighting' 'Psychic'
 'Steel' 'Ice' 'Rock' 'Water']

Combat Power :
 [318 405 525 309 534 314 530 195 205 395 251 349 479 253 413 262 442 288
 438 320 485 300 450 275 365 505 273 323 483 299 270 435 245 455 490 285
 305 265 290 440 500 350 555 385 510 310 400 390 335 515 495 410 315 325
 465 352 460 475 328 330 480 520 425 340 345 295 200 540 535 355 580 420
 600 680]

HP :
 [ 45  60  80  39  58  78  44  59  79  50  40  65  63  83  30  55  35  75
  70  90  46  61  81  95  38  73 115 140  10  25  52 105  85 250  20 130
  48 160  41  91 106 100]

Attack :
 [ 49  62  82  52  64  84  48  63  83  30  20  45  35  25  90  60  80  56
  81  85  55  75 100  47  92  57  72 102  70  41  76  50  65  95 105 110
 130  40 120  73   5  67 125  10 115 134]

Defense :
 [ 49  63  83  43  58  78  65  80 100  35  55  50  30  40  75  60  44  69
  85 110  52  67  87  57  77  48  73  20  45  70  25  95  15 115 130 180
 160  90  53  79 120   5 125 105]

Sp. Atk :
 [ 65  80 100  60 109  50  85  20  25  90  45  35  70  31  61  40  55  75
  95  81  30 110 105 120 135  58 115 130  43  73 125  15  48 154]

Sp. Def :
 [ 65  80 100  50  85  64 105  20  25  35  70  31  61  54  79  30  55  40
  75  90  45  95  60 120  62 115 110  48 125]

Speed :
 [ 45  60  80  65 100  43  58  78  30  70  50  35  75  56  71 101  72  97
  55  90 110  40  41  76  85  20  25  95 120 115 105  15  42  67 150  87
  63  68  93  81  48 130]

Generation :
 [1]

Legendary :
 [False  True]

In [6]:
pk['Type 2'].unique()

array(['Poison', nan, 'Flying', 'Ground', 'Fairy', 'Grass', 'Fighting',
       'Psychic', 'Steel', 'Ice', 'Rock', 'Water'], dtype=object)

In [7]:
pk['Type 2'].fillna(d['Type 2'][3],inplace=True)
pk

C:\Users\mishr\AppData\Local\Temp\ipykernel_35388\2461627003.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pk['Type 2'].fillna(d['Type 2'][3],inplace=True)
C:\Users\mishr\AppData\Local\Temp\ipykernel_35388\2461627003.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pk['Type 2'].fillna(d['Type 2'][3],inplace=True)

,Name,Type 1,Type 2,Combat Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Charmander,Fire,19,309,39,52,43,60,50,65,1,False
4,Charmeleon,Fire,19,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
146,Dratini,Dragon,19,300,41,64,45,50,50,50,1,False
147,Dragonair,Dragon,19,420,61,84,65,70,70,70,1,False
148,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
149,Mewtwo,Psychic,19,680,106,110,90,154,90,130,1,True
150,Mew,Psychic,19,600,100,100,100,100,100,100,1,True

In [8]:
pk.isnull().sum()

Name            0
Type 1          0
Type 2          0
Combat Power    0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64